# Generated by Django 5.1.6 on 2025-03-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')], default='Available', max_length=10),
        ),
    ]
